# Generated by Django 6.0.7 on 2026-07-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seed_categories_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='is_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
