# Generated by Django 6.0.7 on 2026-07-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promo/')),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('cta_label', models.CharField(blank=True, default='Discover', max_length=50)),
                ('cta_link', models.CharField(blank=True, default='/shop', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
