# Generated by Django 6.0.7 on 2026-07-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_promobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='show_button',
            field=models.BooleanField(default=True),
        ),
    ]
