# Generated by Django 6.0.7 on 2026-08-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
