# Generated by Django 6.0.7 on 2026-08-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_announcement_date_from_announcement_date_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promobanner',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='promobanner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
