# Generated by Django 6.0.7 on 2026-08-03 08:46

from django.db import migrations, models


def copy_fabric_to_description(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.description = product.fabric
        product.save(update_fields=['description'])


def copy_description_to_fabric(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.fabric = product.description
        product.save(update_fields=['fabric'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_promobanner_options_promobanner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(copy_fabric_to_description, copy_description_to_fabric),
        migrations.RemoveField(
            model_name='product',
            name='fabric',
        ),
    ]
