# Generated by Django 6.0.7 on 2026-07-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Registration')], max_length=20),
        ),
    ]
