# Generated by Django 6.0.7 on 2026-08-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_otp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Registration'), ('mpin_reset', 'MPIN Reset')], max_length=20),
        ),
    ]
